### ISSUE TITLE
Rozjechane gui

### ISSUE THREAD

**Issue by Shira16** [Damenus/RougeTyper#13]
Po zginięciu w walce i wpisaniu sie na HoF nie pokazała mi się lista graczy na HoF. Ekran wygląda jak na załączonym screenie
![issue1](https://user-images.githubusercontent.com/26346253/41507593-b247912e-7235-11e8-8daa-c52360edac27.png)

**Comment by Averso** [comment]
trzeba utawiać te elementy na pusty tekst
